# Generated by Django 3.1.5 on 2021-02-03 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('simptom1', models.CharField(max_length=50)),
                ('simptom2', models.CharField(max_length=50)),
                ('simptom3', models.CharField(max_length=50)),
                ('simptom4', models.CharField(max_length=50)),
                ('simptom5', models.CharField(max_length=50)),
                ('prediction', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
