from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Symptoms(models.Model):
    symptoms_choices = [
        ('None','Select'),
        ('itching', 'Itching'),
        ('skin_rash', 'Skin Rash'),
        ('nodal_skin_eruptions', 'Nodal Skin Eruptions'),
        ('continuous_sneezing', 'Continuous Sneezing'),
        ('shivering','Shivering'),
        ('chills', 'Chills'),
        ('joint_pain', 'Joint Pain'),
        ('stomach_pain', 'Stomach Pain'),
        ('acidity','Acidity'),
        ('ulcers_on_tongue', 'Ulcers on Tongue'),
        ('muscle_wasting', 'Mucle Wasting'),
        ('vomiting', 'Vomiting'),
        ('burning_micturition', 'Burning Micturition'),
        ('spotting_ urination', 'Spotting Urination'),
        ('fatigue', 'Fatigue'),
        ('weight_gain','Weight Gain'),
        ('anxiety','Anxiety',),
        ('cold_hands_and_feets','Cold Hands and Feets'),
        ('mood_swings','Mood Swings'),
        ('weight_loss','Weight Loss'),
        ('restlessness','Restlessness'),
        ('lethargy','Lethargy'),
        ('patches_in_throat','Patches in Throat'),
        ('irregular_sugar_level','Irregular Sugar Level'),
        ('cough','Cough'),
        ('high_fever','High Fever'),
        ('sunken_eyes','Sunken Eyes'),
        ('breathlessness','Breathlessness'),
        ('sweating','Sweating'),
        ('dehydration','Dehydration'),
        ('indigestion','Indigestion'),
        ('headache','Headache'),
        ('yellowish_skin','Yellowish Skin'),
        ('dark_urine','Dark Urine'),
        ('nausea','Nausea'),
        ('loss_of_appetite','Loss of Appetite'),
        ('pain_behind_the_eyes','Pain Behind the Eyes'),
        ('back_pain','Back Pain'),
        ('constipation','Constipation'),
        ('abdominal_pain','Abdominal Pain'),
        ('diarrhoea','Diarrhoea'),
        ('mild_fever','Mild Fever'),
        ('yellow_urine','Yellow Urine'),
        ('yellowing_of_eyes','Yellowing of Eyes'),
        ('acute_liver_failure','Acute Liver Failure'),
        ('fluid_overload','Fluid Overload'),
        ('swelling_of_stomach','Swelling of Stomach'),
        ('swelled_lymph_nodes','Swelled Lymph Nodes'),
        ('malaise','Malaise'),
        ('blurred_and_distorted_vision','Blurred and Distorted Vision'),
        ('phlegm','Phlegm'),
        ('throat_irritation','Throat Irritation'),
        ('redness_of_eyes','Redness of Eyes'),
        ('sinus_pressure','Sinus Pressure'),
        ('runny_nose','Runny Nose'),
        ('congestion','Congestion'),
        ('chest_pain','Chest Pain'),
        ('weakness_in_limbs','Weakness in Limbs'),
        ('fast_heart_rate','Fast Heart Rate'),
        ('pain_during_bowel_movements','Pain During Bowel Movements'),
        ('pain_in_anal_region','Pain in Anal Region'),
        ('bloody_stool','Bloody Stool'),
        ('irritation_in_anus','Irritation in Anus'),
        ('neck_pain','Neck Pain'),
        ('dizziness','Dizziness'),
        ('cramps','Cramps'),
        ('bruising','Brusing'),
        ('obesity','Obesity'),
        ('swollen_legs','Swollen Legs'),
        ('swollen_blood_vessels','Swollen Blood Vessels'),
        ('puffy_face_and_eyes','Puffy Face and Eyes'),
        ('enlarged_thyroid','Enlarged Thyroid'),
        ('brittle_nails','Brittle Nails'),
        ('swollen_extremeties','Swollen Extremeties'),
        ('excessive_hunger','Excessive Hunger'),
        ('extra_marital_contacts','Extra Marital Contacts'),
        ('drying_and_tingling_lips','Drying and Tingling Lips'),
        ('slurred_speech','Slurred Speech'),
        ('knee_pain','Knee Pain'),
        ('hip_joint_pain','Hip Joint Pain'),
        ('muscle_weakness','Muscle Weakness'),
        ('stiff_neck','Stiff Neck'),
        ('swelling_joints','Swelling Joints'),
        ('movement_stiffness','Movement Stiffness'),
        ('spinning_movements','Spinning Movements'),
        ('loss_of_balance','Loss of Balance'),
        ('unsteadiness','Unsteadiness'),
        ('weakness_of_one_body_side','Weakness of One Body Side'),
        ('loss_of_smell','Loss of Smell'),
        ('bladder_discomfort','Bladder Discomfort'),
        ('foul_smell_of urine','Foul Smell of Urine'),
        ('continuous_feel_of_urine','Continuous Feel of Urine'),
        ('passage_of_gases','Passage of Gases'),
        ('internal_itching','Internal Itching'),
        ('toxic_look_(typhos)','Toxic Look (Typhos)'),
        ('depression','Depression'),
        ('irritability','Irritability'),
        ('muscle_pain','Muscle Pain'),
        ('altered_sensorium','Altered Sensorium'),
        ('red_spots_over_body','Red Spots over body'),
        ('belly_pain','Belly Pain'),
        ('abnormal_menstruation','Abnormal Mestruation'),
        ('dischromic _patches','Dischormic Patches'),
        ('watering_from_eyes','Watering From Eyes'),
        ('increased_appetite','Increased Appetite'),
        ('polyuria','Polyuria'),
        ('family_history','Family History'),
        ('mucoid_sputum','Mycoid Sputum'),
        ('rusty_sputum','Rusty Sputum'),
        ('lack_of_concentration','Lack of Concentration'),
        ('visual_disturbances','Visual Disturbances'),
        ('receiving_blood_transfusion','Receiving Blood Transfusion'),
        ('receiving_unsterile_injections','Receiving Unsterile Injections'),
        ('coma','Coma'),
        ('stomach_bleeding','Stomach Bleeding'),
        ('distention_of_abdomen','Distention of Abdomen'),
        ('history_of_alcohol_consumption','History of Alcohol Comsumption'),
        ('fluid_overload','Fluid Overload'),
        ('blood_in_sputum','Blood in Sputum'),
        ('prominent_veins_on_calf','Prominent Veins on Calf'),
        ('palpitations','Palpitations'),
        ('painful_walking','Painful Walking'),
        ('pus_filled_pimples','Pus Filled Pimples'),
        ('blackheads','Blackheads'),
        ('scurring','Scurring'),
        ('skin_peeling','Skin Peeling'),
        ('silver_like_dusting','Silver Like Dusting'),
        ('small_dents_in_nails','Small Dents in Nails'),
        ('inflammatory_nails','Inflammatory Nails'),
        ('blister','Blister'),
        ('red_sore_around_nose','Red Sore Around Nose'),
        ('yellow_crust_ooze','Yellow Crust Ooze'),
    ]

    def symptomList(self):
        return sorted(self.symptoms_choices)

class DataEntry(models.Model):
    user_id = models.ForeignKey(User, related_name='data', blank=True, null=True, on_delete=models.CASCADE) #here is the class of the user model
    date = models.DateField(auto_now_add=True)
    symptom1 = models.CharField(max_length=50)
    symptom2 = models.CharField(max_length=50)
    symptom3 = models.CharField(max_length=50)
    symptom4 = models.CharField(max_length=50)
    symptom5 = models.CharField(max_length=50)
    diagnosis = models.CharField(max_length=50)

    def __str__(self):
        return f'{ self.id, self.date, self.diagnosis}'

    def get_user_history(request, id):
        return 'blah blah'
